# Generated by Django 5.1.7 on 2025-06-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=400)),
                ('price', models.IntegerField(default=0)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
